excludes:
  - policy_name: action_ref_should_be_full_length_commit_sha
    action_name: guitarrapc/actions/.github/actions/*
  - policy_name: action_ref_should_be_full_length_commit_sha
    action_name: guitarrapc/actions/.github/workflows/*
