using FeatherQR.SkiaSharp;
using SkiaSharp;
namespace FeatherQR.Tests;

/// <summary>
/// The committed external-encoder rMQR fixture corpus (Fixtures/RmQr/), generated by
/// tools/QRInteropFixtures from two independent encoder lineages (libzint via the
/// pinned ZXingCpp package, and the pinned Rust qrtool binary); every fixture passed
/// the zxing-cpp decode sanity gate (raw-byte payload, version, ECC) before being
/// committed. Regenerate with:
/// <c>dotnet run --project tools/QRInteropFixtures -- regenerate</c>
/// (the qrtool binary comes from <c>tools/QRInteropFixtures/get-qrtool.ps1</c>).
/// <para>
/// Phase 5.1a scaffolding: this class pins the corpus SHAPE (both lineages present,
/// every version covered, manifests internally consistent, matrices rectangular and
/// dimensionally exact). The table oracle tests (Phase 5.1b) and the decode
/// assertions (Phase 6.4 matrix path, Phase 7 image path) are added here as those
/// phases land.
/// </para>
/// </summary>
public class RmQrFixtureTest
{
    /// <summary>The 32 rMQR versions (height, width) in ISO/IEC 23941 index order (height-major).</summary>
    public static readonly (int Height, int Width)[] Versions =
    [
        (7, 43), (7, 59), (7, 77), (7, 99), (7, 139),
        (9, 43), (9, 59), (9, 77), (9, 99), (9, 139),
        (11, 27), (11, 43), (11, 59), (11, 77), (11, 99), (11, 139),
        (13, 27), (13, 43), (13, 59), (13, 77), (13, 99), (13, 139),
        (15, 43), (15, 59), (15, 77), (15, 99), (15, 139),
        (17, 43), (17, 59), (17, 77), (17, 99), (17, 139),
    ];

    public static IEnumerable<string> FixtureIds() => FixtureLoader.EnumerateFixtureIds("RmQr");

    [Test]
    public async Task FixtureCorpus_ContainsBothLineages()
    {
        var ids = FixtureIds().ToArray();

        await Assert.That(ids.Any(static id => id.StartsWith("zint-libzint/", StringComparison.Ordinal))).IsTrue();
        await Assert.That(ids.Any(static id => id.StartsWith("qrtool/", StringComparison.Ordinal))).IsTrue();
    }

    [Test]
    public async Task FixtureCorpus_CoversEveryVersion_InBothLineages_AndBothEccLevels()
    {
        var manifests = FixtureIds().Select(id => FixtureLoader.Load("RmQr", id).Manifest).ToArray();

        foreach (var (height, width) in Versions)
        {
            var name = $"R{height}x{width}";
            var ofVersion = manifests.Where(m => m.VersionName == name).ToArray();

            await Assert.That(ofVersion.Any(m => m.Generator == "zint-libzint")).IsTrue()
                .Because($"{name} must have a libzint fixture");
            await Assert.That(ofVersion.Any(m => m.Generator == "qrtool")).IsTrue()
                .Because($"{name} must have a qrtool fixture");
            await Assert.That(ofVersion.Any(m => m.ErrorCorrectionLevel == "M")).IsTrue()
                .Because($"{name} must appear at ECC M");
            await Assert.That(ofVersion.Any(m => m.ErrorCorrectionLevel == "H")).IsTrue()
                .Because($"{name} must appear at ECC H");
        }

        // The libzint sweep carries one single-character case per version × mode
        // (these pin the count-indicator widths in Phase 5.1b).
        foreach (var (height, width) in Versions)
        {
            foreach (var mode in new[] { "Numeric", "Alphanumeric", "Byte" })
            {
                await Assert.That(manifests.Any(m => m.Generator == "zint-libzint" && m.VersionName == $"R{height}x{width}" && m.Mode == mode && m.PayloadText.Length == 1)).IsTrue()
                    .Because($"R{height}x{width} {mode} needs a one-character libzint fixture");
            }
        }

        // UTF-8 byte payloads ride the qrtool lineage.
        await Assert.That(manifests.Any(m => m.Generator == "qrtool" && m.PayloadText.Any(c => c > 0x7F))).IsTrue();
    }

    [Test]
    [MethodDataSource(nameof(FixtureIds))]
    public async Task Fixture_ManifestAndMatrix_AreConsistent(string fixtureId)
    {
        var fixture = FixtureLoader.Load("RmQr", fixtureId);
        var manifest = fixture.Manifest;

        await Assert.That(manifest.SymbolType).IsEqualTo("rMQR");
        await Assert.That(Versions.Contains((manifest.Height, manifest.Width))).IsTrue();
        var index = Array.IndexOf(Versions, (manifest.Height, manifest.Width));
        await Assert.That(manifest.Version).IsEqualTo(index + 1);                       // RmQRVersion / libzint numbering
        await Assert.That(manifest.VersionName).IsEqualTo($"R{manifest.Height}x{manifest.Width}");
        await Assert.That(new[] { "M", "H" }.Contains(manifest.ErrorCorrectionLevel)).IsTrue();
        await Assert.That(new[] { "Numeric", "Alphanumeric", "Byte", "Kanji" }.Contains(manifest.Mode)).IsTrue();
        await Assert.That(manifest.MaskPattern).IsEqualTo(4);                            // reader-sourced: rMQR's single mask = Standard QR pattern 4
        await Assert.That(manifest.QuietZoneModules).IsEqualTo(2);
        await Assert.That(manifest.EciCharset).IsNull();
        await Assert.That(Convert.ToHexString(System.Text.Encoding.UTF8.GetBytes(manifest.PayloadText))).IsEqualTo(manifest.PayloadUtf8Hex);

        var (modules, width, height) = FixtureLoader.ReadRectangularMatrix(fixture.MatrixPath);
        await Assert.That(width).IsEqualTo(manifest.Width);
        await Assert.That(height).IsEqualTo(manifest.Height);
        await Assert.That(modules.Length).IsEqualTo(width * height);

        // Structural invariants every rMQR symbol shares (independent of tables):
        // top-left finder corner dark, bottom-right sub-finder corner dark, and the
        // top / bottom timing rows dark at even columns.
        await Assert.That(modules[0]).IsEqualTo((byte)1);
        await Assert.That(modules[(height - 1) * width + (width - 1)]).IsEqualTo((byte)1);
        for (var col = 8; col < width; col += 2)
        {
            await Assert.That(modules[col]).IsEqualTo((byte)1).Because($"top timing row, col {col} ({fixtureId})");
            await Assert.That(modules[(height - 1) * width + col]).IsEqualTo((byte)1).Because($"bottom timing row, col {col} ({fixtureId})");
        }

        using var bitmap = SKBitmap.Decode(fixture.PngPath);
        await Assert.That(bitmap).IsNotNull();
        await Assert.That(bitmap.Width).IsEqualTo((manifest.Width + 2 * manifest.QuietZoneModules) * manifest.PixelsPerModule);
        await Assert.That(bitmap.Height).IsEqualTo((manifest.Height + 2 * manifest.QuietZoneModules) * manifest.PixelsPerModule);
    }

    /// <summary>
    /// Decodes every committed external symbol through the public matrix path. Payload,
    /// version and ECC must match the manifest; libzint symbols decode with zero
    /// corrections, qrtool symbols with at most one (its documented tail defect drops
    /// low bits of the final ECC codeword on versions 11 modules high or taller).
    /// </summary>
    [Test]
    [MethodDataSource(nameof(FixtureIds))]
    public async Task Decode_MatrixFixture_PayloadAndMetadataMatch(string fixtureId)
    {
        var fixture = FixtureLoader.Load("RmQr", fixtureId);
        var manifest = fixture.Manifest;
        var (modules, width, height) = FixtureLoader.ReadRectangularMatrix(fixture.MatrixPath);

        var success = RmQRCodeDecoder.TryDecode(modules, width, height, out var text, out var info);

        await Assert.That(success).IsTrue().Because(fixtureId);
        await Assert.That(text).IsEqualTo(manifest.PayloadText);
        await Assert.That((int)info.Version).IsEqualTo(manifest.Version);
        await Assert.That(info.EccLevel).IsEqualTo(Enum.Parse<RmQREccLevel>(manifest.ErrorCorrectionLevel));
        var allowedErrors = manifest.Generator == "qrtool" && height >= 11 ? 1 : 0;
        await Assert.That(info.ErrorsCorrected).IsLessThanOrEqualTo(allowedErrors).Because(fixtureId);

        // The PNG carries the same modules (rendered at 8 px/module with a 2-module quiet zone):
        // sample the module centers back into a matrix and decode that too.
        using var bitmap = SKBitmap.Decode(fixture.PngPath);
        var ppm = manifest.PixelsPerModule;
        var qz = manifest.QuietZoneModules;
        var sampled = new byte[width * height];
        for (var row = 0; row < height; row++)
            for (var col = 0; col < width; col++)
            {
                var px = bitmap.GetPixel((qz + col) * ppm + ppm / 2, (qz + row) * ppm + ppm / 2);
                sampled[row * width + col] = px.Red < 128 ? (byte)1 : (byte)0;
            }
        await Assert.That(RmQRCodeDecoder.TryDecode(sampled, width, height, out var fromPng, out _)).IsTrue();
        await Assert.That(fromPng).IsEqualTo(manifest.PayloadText);
    }

    /// <summary>
    /// The libzint fixtures decode with zero corrections (the qrtool lineage carries a
    /// documented one-codeword tail defect, so it has no clean baseline to control).
    /// </summary>
    public static IEnumerable<string> LibzintFixtureIds()
        => FixtureIds().Where(static id => id.StartsWith("zint-libzint/", StringComparison.Ordinal));

    /// <summary>
    /// Negative control for the <c>ErrorsCorrected</c> ceiling above: flipping a single
    /// data module in a clean libzint fixture must decode with exactly one corrected
    /// codeword. If the counter were dead (always 0), this test fails, proving the
    /// zero-corrections baseline is not vacuous. The flipped module is the first data
    /// module in placement order (the first bit of interleaved codeword 0), found by
    /// the same zigzag walk the placer uses, over the naive function-module map.
    /// </summary>
    [Test]
    [MethodDataSource(nameof(LibzintFixtureIds))]
    public async Task Decode_MatrixFixtureWithOneFlippedDataModule_ReportsOneCorrectedCodeword(string fixtureId)
    {
        var fixture = FixtureLoader.Load("RmQr", fixtureId);
        var manifest = fixture.Manifest;
        var (modules, width, height) = FixtureLoader.ReadRectangularMatrix(fixture.MatrixPath);

        var (row, col) = FirstDataModule(height, width);
        modules[row * width + col] ^= 1;

        var success = RmQRCodeDecoder.TryDecode(modules, width, height, out var text, out var info);

        await Assert.That(success).IsTrue().Because(fixtureId);
        await Assert.That(text).IsEqualTo(manifest.PayloadText);
        await Assert.That(info.ErrorsCorrected).IsEqualTo(1).Because(fixtureId);
    }

    /// <summary>
    /// First data module in placement order: the module carrying the first bit of
    /// interleaved codeword 0. Mirrors RmQRModulePlacer's zigzag (column pairs from
    /// the right, alternating up/down, function modules skipped).
    /// </summary>
    private static (int Row, int Col) FirstDataModule(int height, int width)
    {
        var function = RmQRNaiveReference.FunctionModuleMap(height, width);
        var upward = true;
        for (var col = width - 2; col >= 1; col -= 2)
        {
            for (var step = 0; step < height; step++)
            {
                var row = upward ? height - 1 - step : step;
                foreach (var c in new[] { col, col - 1 })
                {
                    if (!function[row * width + c])
                        return (row, c);
                }
            }
            upward = !upward;
        }
        throw new InvalidOperationException("no data module found");
    }

    /// <summary>
    /// Decodes every committed external PNG through the public image path (detection +
    /// sampling + matrix decode). Same expectations as the matrix path.
    /// </summary>
    [Test]
    [MethodDataSource(nameof(FixtureIds))]
    public async Task Decode_PngFixture_PayloadAndMetadataMatch(string fixtureId)
    {
        var fixture = FixtureLoader.Load("RmQr", fixtureId);
        var manifest = fixture.Manifest;

        using var bitmap = SKBitmap.Decode(fixture.PngPath);
        await Assert.That(bitmap).IsNotNull();

        var success = RmQRCodeDecoder.TryDecode(bitmap, out var text, out var info);

        await Assert.That(success).IsTrue().Because($"{fixtureId}: {info.Status}");
        await Assert.That(text).IsEqualTo(manifest.PayloadText);
        await Assert.That((int)info.Version).IsEqualTo(manifest.Version);
        await Assert.That(info.EccLevel).IsEqualTo(Enum.Parse<RmQREccLevel>(manifest.ErrorCorrectionLevel));
        var allowedErrors = manifest.Generator == "qrtool" && bitmap.Height / manifest.PixelsPerModule - 2 * manifest.QuietZoneModules >= 11 ? 1 : 0;
        await Assert.That(info.ErrorsCorrected).IsLessThanOrEqualTo(allowedErrors).Because(fixtureId);
    }
}
