using SkiaSharp.QrCode.Image;

var today = DateTime.Now.ToString("yyyyMMdd_HHmmss");
var content = $"This is a sample message generated by SkiaSharp.QrCode.";
var path = $"bin/output/{today}.png";

// prepare
var fullPath = Path.GetFullPath(path);
var dir = Path.GetDirectoryName(fullPath) ?? throw new ArgumentException($"Invalid file path: no directory component found ('{fullPath}')");
Directory.CreateDirectory(dir);

// generate qr code
var qrCodeData = QRCodeImageBuilder.GetPngBytes(content);
File.WriteAllBytes(path, qrCodeData);

Console.WriteLine($"Successfully output QRCode in {fullPath}");
