using SkiaSharp;
using SkiaSharp.QrCode.Image;

var today = DateTime.Now.ToString("yyyyMMdd_HHmmss");
var content = $"This is a sample message generated by SkiaSharp.QrCode.";
var path = $"bin/output/{today}.png";

// prepare
var fullPath = Path.GetFullPath(path);
var dir = Path.GetDirectoryName(fullPath);
Directory.CreateDirectory(dir);

// generate qr code
var qrCode = new QrCode(content, new Vector2Slim(512, 512), SKEncodedImageFormat.Png);
using (var output = new FileStream(fullPath, FileMode.OpenOrCreate))
{
    qrCode.GenerateImage(output);
}

Console.WriteLine($"Successfully output QRCode in {fullPath}");
