services:
  net:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    command: bash -eux entrypoint.sh -f net8.0
    working_dir: /src
    volumes:
      - ./8.0:/src
      - ./entrypoint.sh:/src/entrypoint.sh:ro
      - ./Program.cs:/src/Program.cs:ro

  nodep:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    command: bash -eux entrypoint.sh -f net8.0
    working_dir: /src
    volumes:
      - ./8.0_nodep:/src
      - ./entrypoint_nodep.sh:/src/entrypoint.sh:ro
      - ./Program.cs:/src/Program.cs:ro
