namespace SkiaSharp.QrCode.Tests;

/// <summary>
/// Decodes the committed external-encoder fixture corpus (Fixtures/MicroQr/) with
/// this library's Micro QR decoder. The corpus is generated by
/// tools/QrInteropFixtures from two independent encoder lineages (libzint via the
/// pinned ZXingCpp package, and the pinned Rust qrtool binary), and every fixture
/// passed the zxing-cpp decode sanity gate before being committed. Regenerate with:
/// <c>dotnet run --project tools/QrInteropFixtures -- regenerate</c>
/// (the qrtool binary comes from <c>tools/QrInteropFixtures/get-qrtool.ps1</c>).
/// <para>
/// Both the matrix path and the PNG image path (Phase 4b image detection) are
/// exercised against every fixture.
/// </para>
/// </summary>
public class MicroQrFixtureTest
{
    public static IEnumerable<string> FixtureIds() => FixtureLoader.EnumerateFixtureIds("MicroQr");

    [Test]
    public async Task FixtureCorpus_ContainsBothLineages()
    {
        var ids = FixtureIds().ToArray();

        await Assert.That(ids.Any(static id => id.StartsWith("zint-libzint/", StringComparison.Ordinal))).IsTrue();
        await Assert.That(ids.Any(static id => id.StartsWith("qrtool/", StringComparison.Ordinal))).IsTrue();
    }

    [Test]
    [MethodDataSource(nameof(FixtureIds))]
    public async Task Decode_MatrixFixture_PayloadAndMetadataMatch(string fixtureId)
    {
        var fixture = FixtureLoader.Load("MicroQr", fixtureId);
        var manifest = fixture.Manifest;
        var (modules, size) = FixtureLoader.ReadMatrix(fixture.MatrixPath);

        await Assert.That(size).IsEqualTo(manifest.Width);

        var success = MicroQrCodeDecoder.TryDecode(modules, size, out var text, out var info);

        await Assert.That(success).IsTrue();
        await Assert.That(text).IsEqualTo(manifest.PayloadText);
        await Assert.That((int)info.Version).IsEqualTo(manifest.Version);
        await Assert.That(info.EccLevel).IsEqualTo(Enum.Parse<MicroQrEccLevel>(manifest.ErrorCorrectionLevel));
        await Assert.That(info.ErrorsCorrected).IsEqualTo(0);
        if (manifest.MaskPattern >= 0)
        {
            await Assert.That(info.MaskPattern).IsEqualTo(manifest.MaskPattern);
        }
    }

    [Test]
    [MethodDataSource(nameof(FixtureIds))]
    public async Task Decode_PngFixture_PayloadAndMetadataMatch(string fixtureId)
    {
        var fixture = FixtureLoader.Load("MicroQr", fixtureId);
        var manifest = fixture.Manifest;

        using var bitmap = SKBitmap.Decode(fixture.PngPath);
        await Assert.That(bitmap).IsNotNull();

        var success = MicroQrCodeDecoder.TryDecode(bitmap, out var text, out var info);

        await Assert.That(success).IsTrue();
        await Assert.That(text).IsEqualTo(manifest.PayloadText);
        await Assert.That((int)info.Version).IsEqualTo(manifest.Version);
        await Assert.That(info.EccLevel).IsEqualTo(Enum.Parse<MicroQrEccLevel>(manifest.ErrorCorrectionLevel));
    }
}
