using FeatherQR.SkiaSharp;
using SkiaSharp;
namespace FeatherQR.Tests;

/// <summary>
/// Decodes the committed external-encoder fixture corpus (Fixtures/StandardQr/)
/// with this library's decoder. The corpus is generated by tools/QRInteropFixtures
/// from independent encoders, so these tests verify the decoder against symbols
/// this library did not produce. Regenerate with:
/// <c>dotnet run --project tools/QRInteropFixtures -- regenerate</c>
/// </summary>
public class StandardQrFixtureTest
{
    public static IEnumerable<string> FixtureIds() => FixtureLoader.EnumerateFixtureIds("StandardQr");

    [Test]
    public async Task FixtureCorpus_IsNotEmpty()
    {
        await Assert.That(FixtureIds().Any()).IsTrue();
    }

    [Test]
    [MethodDataSource(nameof(FixtureIds))]
    public async Task Decode_MatrixFixture_PayloadAndMetadataMatch(string fixtureId)
    {
        var fixture = FixtureLoader.Load("StandardQr", fixtureId);
        var manifest = fixture.Manifest;
        var (modules, size) = FixtureLoader.ReadMatrix(fixture.MatrixPath);

        await Assert.That(size).IsEqualTo(manifest.Width);

        var success = QRCodeDecoder.TryDecode(modules, size, out var text, out var info);

        await Assert.That(success).IsTrue();
        await Assert.That(text).IsEqualTo(manifest.PayloadText);
        await Assert.That(info.Version).IsEqualTo(manifest.Version);
        await Assert.That(info.EccLevel).IsEqualTo(Enum.Parse<ECCLevel>(manifest.ErrorCorrectionLevel));
        await Assert.That(info.ErrorsCorrected).IsEqualTo(0);
        if (manifest.MaskPattern >= 0)
        {
            await Assert.That(info.MaskPattern).IsEqualTo(manifest.MaskPattern);
        }
    }

    /// <summary>
    /// Negative control for the <c>ErrorsCorrected == 0</c> assertion above: flipping a
    /// single data module in the same fixture must decode with exactly one corrected
    /// codeword. If the counter were dead (always 0), this test fails, proving the
    /// clean-fixture assertion is not vacuous. The bottom-right corner module carries
    /// the first bit of codeword 0 in every Standard QR version (codeword placement
    /// starts there), so it is a data module regardless of version.
    /// </summary>
    [Test]
    [MethodDataSource(nameof(FixtureIds))]
    public async Task Decode_MatrixFixtureWithOneFlippedDataModule_ReportsOneCorrectedCodeword(string fixtureId)
    {
        var fixture = FixtureLoader.Load("StandardQr", fixtureId);
        var manifest = fixture.Manifest;
        var (modules, size) = FixtureLoader.ReadMatrix(fixture.MatrixPath);

        modules[(size - 1) * size + (size - 1)] ^= 1;

        var success = QRCodeDecoder.TryDecode(modules, size, out var text, out var info);

        await Assert.That(success).IsTrue().Because(fixtureId);
        await Assert.That(text).IsEqualTo(manifest.PayloadText);
        await Assert.That(info.ErrorsCorrected).IsEqualTo(1).Because(fixtureId);
    }

    [Test]
    [MethodDataSource(nameof(FixtureIds))]
    public async Task Decode_PngFixture_PayloadAndMetadataMatch(string fixtureId)
    {
        var fixture = FixtureLoader.Load("StandardQr", fixtureId);
        var manifest = fixture.Manifest;

        using var bitmap = SKBitmap.Decode(fixture.PngPath);
        await Assert.That(bitmap).IsNotNull();

        var success = QRCodeDecoder.TryDecode(bitmap, out var text, out var info);

        await Assert.That(success).IsTrue();
        await Assert.That(text).IsEqualTo(manifest.PayloadText);
        await Assert.That(info.Version).IsEqualTo(manifest.Version);
        await Assert.That(info.EccLevel).IsEqualTo(Enum.Parse<ECCLevel>(manifest.ErrorCorrectionLevel));
    }
}
