using SkiaSharp;

namespace SkiaSharp.QrCode.Tests;

/// <summary>
/// Decodes the committed external-encoder fixture corpus (Fixtures/StandardQr/)
/// with this library's decoder. The corpus is generated by tools/QRInteropFixtures
/// from independent encoders, so these tests verify the decoder against symbols
/// this library did not produce. Regenerate with:
/// <c>dotnet run --project tools/QRInteropFixtures -- regenerate</c>
/// </summary>
public class StandardQrFixtureTest
{
    public static IEnumerable<string> FixtureIds() => FixtureLoader.EnumerateFixtureIds("StandardQr");

    [Test]
    public async Task FixtureCorpus_IsNotEmpty()
    {
        await Assert.That(FixtureIds().Any()).IsTrue();
    }

    [Test]
    [MethodDataSource(nameof(FixtureIds))]
    public async Task Decode_MatrixFixture_PayloadAndMetadataMatch(string fixtureId)
    {
        var fixture = FixtureLoader.Load("StandardQr", fixtureId);
        var manifest = fixture.Manifest;
        var (modules, size) = FixtureLoader.ReadMatrix(fixture.MatrixPath);

        await Assert.That(size).IsEqualTo(manifest.Width);

        var success = QRCodeDecoder.TryDecode(modules, size, out var text, out var info);

        await Assert.That(success).IsTrue();
        await Assert.That(text).IsEqualTo(manifest.PayloadText);
        await Assert.That(info.Version).IsEqualTo(manifest.Version);
        await Assert.That(info.EccLevel).IsEqualTo(Enum.Parse<ECCLevel>(manifest.ErrorCorrectionLevel));
        if (manifest.MaskPattern >= 0)
        {
            await Assert.That(info.MaskPattern).IsEqualTo(manifest.MaskPattern);
        }
    }

    [Test]
    [MethodDataSource(nameof(FixtureIds))]
    public async Task Decode_PngFixture_PayloadAndMetadataMatch(string fixtureId)
    {
        var fixture = FixtureLoader.Load("StandardQr", fixtureId);
        var manifest = fixture.Manifest;

        using var bitmap = SKBitmap.Decode(fixture.PngPath);
        await Assert.That(bitmap).IsNotNull();

        var success = QRCodeDecoder.TryDecode(bitmap, out var text, out var info);

        await Assert.That(success).IsTrue();
        await Assert.That(text).IsEqualTo(manifest.PayloadText);
        await Assert.That(info.Version).IsEqualTo(manifest.Version);
        await Assert.That(info.EccLevel).IsEqualTo(Enum.Parse<ECCLevel>(manifest.ErrorCorrectionLevel));
    }
}
