using SkiaSharp.QrCode;
using ZXingCpp;

namespace QrInteropFixtures;

/// <summary>
/// Encoder interoperability spot check: symbols generated by SkiaSharp.QrCode's
/// Micro QR encoder are rendered to luminance images in memory and decoded with
/// zxing-cpp (via the ZXingCpp .NET wrapper) — an independent implementation
/// lineage. This is the external verification required by the encoder MVT until
/// the interop CI pipeline exists.
/// </summary>
public static class MicroQrSpotCheck
{
    private const int QuietZoneModules = 2; // Micro QR specification quiet zone
    private const int PixelsPerModule = 8;

    private static readonly (string Text, MicroQrEccLevel Ecc)[] cases =
    [
        ("12345", MicroQrEccLevel.ErrorDetectionOnly),  // M1
        ("0123456789", MicroQrEccLevel.L),              // M2-L boundary
        ("12345678", MicroQrEccLevel.M),                // M2-M boundary
        ("HELLO WORLD 14", MicroQrEccLevel.L),          // M3-L alphanumeric boundary
        ("byte hi", MicroQrEccLevel.M),                 // M3-M byte
        ("HELLO WORLD PLUS 21ST", MicroQrEccLevel.L),   // M4-L alphanumeric boundary
        ("bytes m4 mode", MicroQrEccLevel.M),           // M4-M byte boundary
        ("bytes!!!!", MicroQrEccLevel.Q),               // M4-Q byte boundary
        ("こんにちは", MicroQrEccLevel.L),               // UTF-8 (15 bytes, M4-L, no ECI)
    ];

    public static int Run()
    {
        var reader = new BarcodeReader
        {
            Formats = BarcodeFormat.MicroQRCode,
            TryHarder = true,
        };

        var failures = 0;
        foreach (var (text, ecc) in cases)
        {
            var calculated = MicroQrCodeGenerator.GetRequiredBufferSize(text.AsSpan(), ecc, quietZoneSize: QuietZoneModules);
            var modules = new byte[calculated.BufferSize];
            MicroQrCodeGenerator.CreateMicroQrCode(text.AsSpan(), ecc, modules, quietZoneSize: QuietZoneModules);

            var luminance = RenderLuminance(modules, calculated.QrSize, PixelsPerModule);
            var widthPixels = calculated.QrSize * PixelsPerModule;
            var image = new ImageView(luminance, widthPixels, widthPixels, ImageFormat.Lum);

            var results = reader.From(image);
            if (results.Length == 1 && results[0].Text == text)
            {
                Console.WriteLine($"PASS: {calculated.Version}/{ecc} \"{text}\" decoded as {results[0].Format}");
            }
            else
            {
                failures++;
                var detail = results.Length == 0 ? "not detected" : $"decoded {results.Length} symbol(s), first text \"{results[0].Text}\"";
                Console.Error.WriteLine($"FAIL: {calculated.Version}/{ecc} \"{text}\" -> {detail}");
            }
        }

        Console.WriteLine(failures == 0
            ? $"spot-check-microqr: all {cases.Length} symbols decoded by zxing-cpp"
            : $"spot-check-microqr: {failures}/{cases.Length} FAILED");
        return failures == 0 ? 0 : 1;
    }

    /// <summary>Renders a byte-per-module matrix to an 8-bit luminance image (0 = dark, 255 = light).</summary>
    private static byte[] RenderLuminance(byte[] modules, int matrixSize, int pixelsPerModule)
    {
        var widthPixels = matrixSize * pixelsPerModule;
        var luminance = new byte[widthPixels * widthPixels];

        for (var row = 0; row < matrixSize; row++)
        {
            for (var col = 0; col < matrixSize; col++)
            {
                var value = modules[row * matrixSize + col] != 0 ? (byte)0 : (byte)255;
                var pixelRow = row * pixelsPerModule;
                var pixelCol = col * pixelsPerModule;
                for (var y = 0; y < pixelsPerModule; y++)
                {
                    var offset = (pixelRow + y) * widthPixels + pixelCol;
                    luminance.AsSpan(offset, pixelsPerModule).Fill(value);
                }
            }
        }

        return luminance;
    }
}
