name: build debug

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

env:
  BUILD_CONFIG: Debug

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: guitarrapc/actions/.github/actions/setup-dotnet@main
        with:
          restore-wasm-workload: true
          dotnet-version: |
            9.0.x
            8.0.x
      - name: Build
        run: dotnet build -c ${{ env.BUILD_CONFIG }} SkiaSharp.QrCode.Linux.slnf
      - name: Test
        run: dotnet test -c ${{ env.BUILD_CONFIG }} SkiaSharp.QrCode.sln --logger GitHubActions --logger "console;verbosity=normal"

  run:
    needs: [build]
    strategy:
      matrix:
        dotnet-version: ["8.0"]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: guitarrapc/actions/.github/actions/setup-dotnet@main
        with:
          restore-wasm-workload: true
          dotnet-version: |
            9.0.x
            8.0.x
      # ManualGenerate
      - name: Run ManualGenerate (${{ matrix.dotnet-version}})
        run: dotnet run --project ./ManualGenerate.csproj -c ${{ env.BUILD_CONFIG }} -f net${{ matrix.dotnet-version }}
        working-directory: ./samples/ManualGenerate
      # SimpleGenerate
      - name: Run SimpleGenerate (${{ matrix.dotnet-version}})
        run: dotnet run --project ./samples/SimpleGenerate/SimpleGenerate.csproj -c ${{ env.BUILD_CONFIG }} -f net${{ matrix.dotnet-version }}
      # LinuxRunSamples
      - name: Run Linux Docker Compose (${{ matrix.dotnet-version}})
        run: docker compose -f ./samples/LinuxCompose/compose.override.${{ matrix.dotnet-version }}.yaml up
