name: PR Harness

on:
  pull_request:
    branches: [main]

jobs:
  harness:
    permissions:
      contents: read
      pull-requests: read
    uses: guitarrapc/actions/.github/workflows/pr-harness.yaml@9122a18b0dea07585a242b9eb6ed7886f8587c49 # v1.0.1
